server:
  port: 8083

spring:
  application:
    name: booking-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/booking-service
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations:
      - db.migration
