server:
  port: 8082

spring:
  application:
    name: car-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/car-service
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations:
      - db.migration

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html