server:
  port: 8080

spring:
  application:
    name: user-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations:
      - db.migration