CREATE TABLE bookings(
       id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
       create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
       edit_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
       name VARCHAR(100) NOT NULL,
       user_id UUID NOT NULL,
       car_id UUID NOT NULL
);